insert into parameters(name,unit,description) values ('Precipitação','mm','Precipitação');
insert into parameters(name,unit,description) values ('Pressão Atmosferica','hPa','Pressão Atmosferica');
insert into parameters(name,unit,description) values ('Pressão Atmosférica Máxima','hPa','Pressão Atmosférica Máxima');
insert into parameters(name,unit,description) values ('Pressão Atmosférica Mínima','hPa','Pressão Atmosférica Mínima');
insert into parameters(name,unit,description) values ('Radiacao Global','KJ/M²','Radiacao Global');
insert into parameters(name,unit,description) values ('Temperatura Do Ar','°C','Temperatura Do Ar');
insert into parameters(name,unit,description) values ('Temperatura Do Ponto De Orvalho','°C','Temperatura Do Ponto De Orvalho');
insert into parameters(name,unit,description) values ('Temperatura Máxima','°C','Temperatura Máxima');
insert into parameters(name,unit,description) values ('Temperatura Máxima Do Ponto De Orvalho','°C','Temperatura Máxima Do Ponto De Orvalho');
insert into parameters(name,unit,description) values ('Temperatura Mínima','°C','Temperatura Mínima');
insert into parameters(name,unit,description) values ('Temperatura Mínima Do Ponto De Orvalho','°C','Temperatura Mínima Do Ponto De Orvalho');
insert into parameters(name,unit,description) values ('Umidade Relativa Do Ar','%','Umidade Relativa Do Ar');
insert into parameters(name,unit,description) values ('Umidade Relativa Maxima Do Ar','%','Umidade Relativa Maxima Do Ar');
insert into parameters(name,unit,description) values ('Umidade Relativa Minima Do Ar','%','Umidade Relativa Minima Do Ar');
insert into parameters(name,unit,description) values ('Vento Velocidade','m/s','Vento Velocidade');
insert into parameters(name,unit,description) values ('Vento, Direção','graus','Vento, Direção');
insert into parameters(name,unit,description) values ('Vento, Rajada Maxima','m/s','Vento, Rajada Maxima');